language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ibaranov91/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ibaranov91/react-test npm test

after_success:
  - docker build -t ibaranov91/multi-client ./client/Dockerfile ./client
  - docker build -t ibaranov91/multi-nginx ./nginx/Dockerfile ./nginx
  - docker build -t ibaranov91/multi-server ./server/Dockerfile ./server
  - docker build -t ibaranov91/multi-worker ./worker/Dockerfile ./worker
